version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VITE_ENABLE_PERFORMANCE_MONITORING=true
